categories:
  productivity: ["productivity", "time management", "organization", "workflow"]
  communication: ["communication", "collaboration", "team", "messaging"]
  automation: ["automation", "workflow", "process", "efficiency"]
  data: ["data", "analytics", "reporting", "dashboard"]
  marketing: ["marketing", "advertising", "social media", "seo"]
  finance: ["finance", "accounting", "billing", "invoicing"] 